### ISSUE TITLE
Breaks GOG Galaxy installation

### ISSUE THREAD

**Issue by SnowGabe** [jonathanlermitage/tikione-steam-cleaner#13]
Tikione removes redistributable files that are required for GOG Galaxy to function and I'm forced to reinstall. I've reproduced this issue thrice. When I try to launch Galaxy client, I simply get an error. 
Tested also with the latest version of Steam Cleaner.

![2015-06-16 15_57_10-gog galaxy error](https://cloud.githubusercontent.com/assets/11059234/8183527/67915bce-1441-11e5-863d-416d90ad2c7f.png)

**Comment by jonathanlermitage** [comment]
Hi,
Steam Cleaner is not design to support GOG (or any non-Steam platform).

Could you show me the full path of your GOG installation? (something like "C:\Program Files\GOG\", I guess). I'll add this path to the exclude list to prevent corruption. Thx.

**Comment by SnowGabe** [comment]
C:\Program Files (x86)\GalaxyClient

**Comment by jonathanlermitage** [comment]
Thx, I'll add this path asap.

For games installed with non-Steam platform, they simply don't have the Redist Installer problem. 
GOG, Desura and Origin don't leave Redist installers on your system; that's why I don't offer support for these platforms.

Steam Cleaner works with files and folders patterns only, that's why it can work outside of Steam, but I cannot offer a reliable way to detect Redist files for these softwares. Steam uses some generic patterns like 'redist', 'directx' or 'installer', but non-Steam softwares can be very different. Also, they usually come with a single-file installer that already contains and installs Redists. Once your software is installed, you only have delete the single-file installer, there's no Redist Installer left on the system.

**Comment by SnowGabe** [comment]
There are redistributable packages in GOG games. I only have a couple of games installed and I've found:

GOG:
D:\GOG Games\FlatOut 2\__redist
Hotline Miami 2 has the same "__redist" folder. 

Origin:
Battlefield 4: D:\Origin Games\Battlefield 4\__Installer
Bejeweled 3: D:\Origin Games\Bejeweled 3\__Installer
Dragon Age: D:\Origin Games\Dragon Age\__Installer
Medal of Honor Allied Assault: D:\Origin Games\D:\Origin Games\Medal of Honor Allied Assault Warchest\__Installer Warchest\__Installer
Plants vs Zombies Garden Warfare: D:\Origin Games\Plants vs Zombies Garden Warfare\__Installer\vc\vc2012Update3\redist
SimCity 2000: D:\Origin Games\SimCity 2000 SE\__Installer
Sims 3: D:\Origin Games\SimCity 2000 SE\__Installer
Theme Hospital: D:\Origin Games\Theme Hospital\__Installer
Titanfall: D:\Origin Games\Titanfall\__Installer

**Comment by jonathanlermitage** [comment]
Wow, it seems to be new (actually, I have to admit I have not launched GOG/Origin and others since a year ^_^).
Thx a lot for your feedback, I'll add patterns to support these redists. Also, I'll probably add support to autodetect GOG/Origin installation dirs.
Regards,

**Comment by jonathanlermitage** [comment]
I can delete the entire "<aGame>__redist" and "<aGame>__Installer" folders?

**Comment by SnowGabe** [comment]
I have to test more, I'll leave my home now and will be back next week. All games that I launched worked fine without those directories.

**Comment by jonathanlermitage** [comment]
Added "*__redist(s)" and "*__installer" folders to the regular redist list.
Also added Support, Help and EULA in the experimental list.
