### ISSUE TITLE
Farther TikiOne Development

### ISSUE THREAD

**Issue by zQueal** [jonathanlermitage/tikione-steam-cleaner#18]
So, I was reading on Reddit, [specifically this post](https://www.reddit.com/r/pcmasterrace/comments/3mk1m7/tikione_steam_cleaner_is_dead_i_feel_like_we/), and saw that a software that I use relatively regularly (every time I install a Steam game) is stopping development.

After reading through the comments you can see that almost no one knew you ran a fundraiser program for this software. I'd advise you to run it again and advertise on /r/pcmasterrace. Most of us use this software.

Thanks for your hard work, regardless.

**Comment by rappo** [comment]
I second this. I use this tool often (and even follow it on GitHub) and had no idea there was a fundraising campaign.

That said, I'm one of the founders of Bountysource.com and would love to have you try fundraising through Bontysource since we focus 100% on open source projects. Through our new [Salt](https://salt.bountysource.com/) platform we have recurring crowdfunding for opensource projects, but also allow one-off contributions. In addition to that, anyone can put bounties on specific issues/requests right on Bountysource.com.

Since visibility of the campaign was a problem, I can invite you to our private beta of a GitHub emailer we built as part of our updates system. It'll email all of your watchers, stargazers, and forkers (if they have public emails)... this would be a great way to get the word out, in addition to a r/pcmr post like @zQueal suggested.
